name: Flutter Tests

on:
  push:
    branches:
      - '*'

jobs:
  flutter_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1

      - name: Run tests
        run: flutter test
