name: Run Flutter Tests

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 'stable'
          channel: 'stable'
          flutter-root: '$FLUTTER_ROOT'
          cache-flutter: true
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
